### ISSUE TITLE
Cannot run generate script - & missing npm dependencies

### ISSUE THREAD

**Issue by WilliamHF** [code42day/liftie#2]
Problem when trying to use the generate script 

/(...)/liftie/bin/generate:158
  schema[2].before = splitHost;
        ^
TypeError: Cannot read property '2' of undefined
    at execute (/(...)/liftie/bin/generate:158:9)
    at Object.<anonymous> (/(...)/liftie/bin/generate:44:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

Had some problem when trying to npm / make as missing dependencies

npm WARN package.json dirty@0.9.9 No repository field.
npm ERR! fetch failed http://registry.npmjs.eu/methods/-/methods-0.0.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed http://registry.npmjs.eu/methods/-/methods-0.0.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed http://registry.npmjs.eu/methods/-/methods-0.0.1.tgz
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.36
npm ERR! npm  v2.4.1

Latest version is 1.1.1 - 0.0.1 is outdated 

+ on components when trying make :+1: 

node_modules/make-component-shrinkwrap/node_modules/.bin/component-shrinkwrap --install 
make: node_modules/make-component-shrinkwrap/node_modules/.bin/component-shrinkwrap: No such file or directory
make: *** [components] Error 1

had to manually install latest versions

**Comment by pirxpilot** [comment]
I fixed npm-shrinkwrap -  you probably should:

    rm node_modules && npm install

I'll have a look at the generate script later today.

**Comment by pirxpilot** [comment]
`generate` script should run again now.
Thanks for reporting the issue!
Good luck with adding support for European resorts. If you run into any problems just open new issues. Or we can chat on [gitter](https://gitter.im/code42day/liftie)

**Comment by WilliamHF** [comment]
Works great now, thanks for fixing Damian.
Will try adding some resorts and will send you a pull soon
