### ISSUE TITLE
Many resorts broken / need updated URLs

### ISSUE THREAD

**Issue by mikemmb73** [code42day/liftie#9]

**Comment by pirxpilot** [comment]
I went through a cycle of resort updates recently (happens every year). I probably won't have time to update any more, but will gladly review and integrate a pull request / patch for any resort that you care about. Check out Readme on how to add new resorts and ping me if you have any questions.
All-inclusive issue is not that helpful though so I am closing this one.

**Comment by mikemmb73** [comment]
I updated a resort a while ago (crystal-mountain) but it didn’t seem to get accepted.  We are using liftie API for a project hoping releasing before the new year and I have been putting off fixing all the broken resorts for a while.  I was going to move to a privately hosted version, but I would be happy to push all my fixes out to the project as well, whichever is easier for you.  Either way, is there any documentation on how the parsing works?  Ive been trying to piece it together myself and Ive made a little progress, but if you have any internal documentation that would be extremely helpful.  Hopefully I will have patched all resorts before January 1.  Thank you so much for your work on liftie, and I really appreciate all your time.  Thanks!

**Comment by pirxpilot** [comment]
While having your own version with your own fixes is absolutely OK with liftie's [BSD license][1] - as long you retain copyright notice - contributing your fixes back is a good form (not to mention good karma :smile:  ).
Ideally separate issues with one PR for each fixed resort are easiest for me to work with. Even if something is not 100% ready - for example if tests do not quite work - opening a PR gives me a chance to help you with specific questions you might have. The is not *internal* documentation, but... plenty of examples in the code. Looking forward to your fixes.
[1]: https://github.com/code42day/liftie/blob/master/License.md
